services:
  app:
    image: parkjaehyeok/hnh-servers:1
    container_name: hnh-app
    ports:
      - "8080:8080"
    depends_on:
      - nginx
      - redis
      - mysql
    environment:
      - AWS_IAM_ACCESS_KEY=${AWS_IAM_ACCESS_KEY}
      - AWS_IAM_SECRET_KEY=${AWS_IAM_SECRET_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - JPA_HIBERNATE_DDL=${JPA_HIBERNATE_DDL}
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_URL=jdbc:mysql://hnh-mysql:3306/hnh
      - JWT_SECRET=036c4fe3ec667532545b9e8fa7e2a98a22f439dff102623c097715060e2da68c

    env_file:
      - .env


  mysql:
    image: mysql:latest
    container_name: hnh-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=hnh
    ports:
      - "23306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - redis
      - mysql

volumes:
  mysql-data: