name: Docker Compose CI/CD

on:
  push:
    branches:
      - main
      - develop
      - feat/*
  pull_request:
    branches:
      - main
      - develop
      - feat/*

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: make executable gradlew
        run: chmod +x ./gradlew
